### ISSUE TITLE
Consider dropping the try-catch

### ISSUE THREAD

**Issue by Pimm** [Pimm/ruply#2]
### Background

_ruply_ is promise-aware. Instead of passing promises into your callbacks, it awaits them and passes the values to which they resolve instead. This is what the developer intends in almost every scenario.
```javascript
return run(
	database.query(`
		select
			id, title
		from
			books
	`),
	rows => new Map(
		rows.map(({ id, title }) => [id, title])
	)
)
```

In the world of JavaScript ‒ however ‒ "is this a promise?" can be a trickier question than it initially seems.

[ECMAScript has `IsPromise`](https://tc39.es/ecma262/#sec-ispromise) for this purpose. It checks for the existence of an internal slot. _ruply_ can't do that.

It could instead do `candidate instanceof Promise`. This has the downside of discriminating against "fake" promises. Non-globally polyfilled promises would not be considered promises (you may not be using a polyfill, but a library or framework you're using might!). "Fake" promises designed for testing, or logging, or any other purpose, would not be considered promises either. Finally, I feel this goes against the duck typed nature of JavaScript.

[Promises/A+ describes _thenables_](https://promisesaplus.com/#terminology), defined as:
 > an object or function that defines a `then` method.

This definition covers ECMA-style promises, as well as anything else one might expect to be handled like a promise.

_ruply_ currently has `checkThenable`:
```javascript
function checkThenable(input) {
	try {
		var { then } = input
	} catch (error) {
		return false
	}
	return 'function' == typeof then
}
```
The try-catch construction ensures `null` and `undefined` are accurately reported as not being promises, as well as objects like this one:
```javascript
const depositBox = new Proxy({}, {
	get() { throw new Error('Deposits only, please') }
})
```

[Promises/A+ understands the risk of such objects](https://promisesaplus.com/#the-promise-resolution-procedure) as well:
 > If retrieving the property `x.then` results in a thrown exception `e`, reject `promise` with `e` as the reason.

### Issue

We're using _ruply_ in projects in which performance matters, and it seems the try-catch is causing a significant slowdown.

We should figure out:
1. What are the requirements for a `checkThenable` function?
2. How fast or slow are the different alternatives compared to the current implementation?

_is-promise_, a library designed to do the same thing as `checkThenable`, [had a discussion concerning "dangerous objects"](https://github.com/then/is-promise/pull/4) seven years ago. They decided against catching the error. I'm not completely sure whether it's a fair comparison, though. Having `isPromise(dangerousObject)` cause an error is maybe less surprising than having `run(dangerousObject, […])` cause an error.

**Comment by janpaepke** [comment]
We came up with this testing scenario:
```js
const repeat = 20;
const cycles = 5e4;

const testagainst = 1;

function testTryCatch(input) {
	if (null == input) {
		return false;
	}
	try {
		var { then } = input;
	} catch (error) {
		return false;
	}
	return 'function' == typeof then;
}

function testCompare(input) {
	if (
		null != input &&
		['object', 'function'].includes(typeof input) &&
		'then' in input &&
		'function' == typeof input.then
	) {
		return true;
	}
	return false;
}

function test(callbacks) {
	Object.entries(callbacks).forEach(([funcName, callback]) => {
		const measurements = [];
		for (let r = 0; r < repeat; r++) {
			const start = performance.now();
			for (let i = 0; i < cycles; i++) {
				callback.call(null);
			}
			measurements.push(performance.now() - start);
		}
		const average = measurements.reduce((sum, val) => sum + val, 0) / measurements.length;
		console.log(`'${funcName}': ${cycles} cycles took an average of ${average}ms`);
	});
}

test({
	tryCatch: testTryCatch.bind(null, testagainst),
	compare: testCompare.bind(null, testagainst),
});
```

Results when run with `const testagainst = 1`:
```
'tryCatch': 50000 cycles took an average of 1.4340333074331284ms
'compare': 50000 cycles took an average of 2.370340296626091ms
```

Results when run with `const testagainst = undefined`;
```
'tryCatch': 50000 cycles took an average of 1052.3028114467859ms
'compare': 50000 cycles took an average of 1.8933052957057952ms
```

This is on node v16.13.2

### Conclusion: It's not `try/catch` that's slow, it's only `catch`.

The only type of values that throw in this comparison are `null`, `undefined` and objects who throw when accessing their `then` property, like the crafted `depositBox` above.

The problem is that the try catch method more closely matches the spec.

Thus my recommendation is using this implementation:

```js
function getThenIfPromiseLike(input) {
	if (null == input) {
		return;
	}
	try {
		var { then } = input
	} catch (error) {
		return;
	}
	if ('function' != typeof then) {
		return;
	}
	return then;
}
```

This returns the then function, if it's defined, so it can be used.
It will never throw, as @Pimm pointed out it would be surprising if run threw, just because it failed to determine, if something was a promise.
